POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json

{
    "title": "pizza 3",
    "img": "/img/pizza.png",
    "desc":"desc3",
    "prices": [
        12, 13, 14
        ],
    "extraOption":[
        {
        "text": "Extra Saoce",
        "price":2
    }
    ]
}